# Generated by Django 4.1.7 on 2023-02-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="recordcategory",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
