# Generated by Django 4.1.7 on 2023-02-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="record_files")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="archive.record"
                    ),
                ),
            ],
        ),
    ]
