# Generated by Django 4.1.7 on 2023-02-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0004_recordfile_content_type_alter_collection_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordfile",
            name="content_type",
            field=models.CharField(
                default="application/octet-stream",
                max_length=50,
                verbose_name="Content-Type",
            ),
        ),
    ]
