# Generated by Django 4.1.7 on 2023-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_record_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordfile",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Entstehungsjahr"
            ),
        ),
    ]
