# Generated by Django 4.1.7 on 2023-02-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0007_recordfile_thumbnail_alter_record_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordfile",
            name="preview",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Preview"
            ),
        ),
        migrations.AlterField(
            model_name="recordcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
