# Generated by Django 4.1.7 on 2023-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0009_recordtag_alter_record_category_record_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
    ]
