# Generated by Django 4.1.7 on 2023-03-19 10:21

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0010_collection_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordfile",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=archive.models.get_file_path,
                verbose_name="Datei",
            ),
        ),
        migrations.AlterField(
            model_name="recordfile",
            name="preview",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="",
                verbose_name="Preview",
            ),
        ),
        migrations.AlterField(
            model_name="recordfile",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="",
                verbose_name="Thumbnail",
            ),
        ),
    ]
