# Generated by Django 4.1.7 on 2023-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0011_alter_recordfile_file_alter_recordfile_preview_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["origin_date", "year"]},
        ),
        migrations.AddField(
            model_name="record",
            name="origin_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of origin"
            ),
        ),
    ]
