name: Community Archive

on: [push]

jobs:
  build:
    runs-on: debian-bullseye

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
      - name: Configure environment
        run: |
          cp env.sample .env
      - name: Lint with ruff
        run: |
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          ruff --format=github --target-version=py37
      - name: Run django tests
        run: |
          python manage.py test

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
